baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "â†©"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Posts
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; Douglas Dwyer 2023 -- {Year} "

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
